### ISSUE TITLE
Project doesn't compile

### ISSUE THREAD

**Issue by bashan** [Sanoma-CDA/maxmind-geoip2-scala#3]
I cloned the project and ran: +publish-local I get errors.
It seems like the project doesn't compile.

Here here the errors:
------------------------------------------------------------------------------------------------------
> +publish-local
[info] Setting version to 2.9.2
[info] Reapplying settings...
[info] Set current project to maxmind-geoip2-scala (in build file:/C:/repository/maxmind-geoip2-scala/)
[info] Wrote C:\repository\maxmind-geoip2-scala\target\scala-2.9.2\maxmind-geoip2-scala_2.9.2-1.3.2.pom
[info] :: delivering :: com.sanoma.cda#maxmind-geoip2-scala_2.9.2;1.3.2 :: 1.3.2 :: release :: Sat Feb 07 23:08:44 IST 2015
[info]  delivering ivy file to C:\repository\maxmind-geoip2-scala\target\scala-2.9.2\ivy-1.3.2.xml
[info] Compiling 7 Scala sources to C:\repository\maxmind-geoip2-scala\target\scala-2.9.2\classes...
[info] Main Scala API documentation to C:\repository\maxmind-geoip2-scala\target\scala-2.9.2\api...
[error] error while loading CharSequence, class file 'C:\Program Files\Java\jre1.8.0_25\lib\rt.jar(java/lang/CharSequence.class)' is broken
[error] (bad constant pool tag 15 at byte 1470)
[error] error while loading CharSequence, class file 'C:\Program Files\Java\jre1.8.0_25\lib\rt.jar(java/lang/CharSequence.class)' is broken
[error] (bad constant pool tag 15 at byte 1470)
[error] error while loading Comparator, class file 'C:\Program Files\Java\jre1.8.0_25\lib\rt.jar(java/util/Comparator.class)' is broken
[error] (bad constant pool tag 15 at byte 4972)
[error] error while loading Comparator, class file 'C:\Program Files\Java\jre1.8.0_25\lib\rt.jar(java/util/Comparator.class)' is broken
[error] (bad constant pool tag 15 at byte 4972)
[error] C:\repository\maxmind-geoip2-scala\src\main\scala\com\sanoma\cda\geo\GeoArea.scala:145: could not find implicit value for parameter num: Numeric[Int]
[error]     }.sum
[error]       ^
[error] C:\repository\maxmind-geoip2-scala\src\main\scala\com\sanoma\cda\geo\GeoArea.scala:145: could not find implicit value for parameter num: Numeric[Int]
[error]     }.sum
[error]       ^
[error] three errors found
[info] No documentation generated with unsucessful compiler run
[error] three errors found
[error] (compile:doc) Scaladoc generation failed
[error] (compile:compile) Compilation failed
[error] Total time: 7 s, completed 23:08:51 07/02/2015

**Comment by hgavert** [comment]
Hi!

I can't reproduce your error. I just did fresh clone and downloaded the DB file with wget. (With the current DB file, some test locations had changed, so I'll update the tests.) For me tests ran ok, same with +publish-local. No errors.

I'm developing on OS X, so I'm not sure if there is some funny problem with platforms. I've had some problems with Scala generating too long filenames, but your problem doesn't seem like it. I'm not sure what's wrong.

**Comment by hgavert** [comment]
I changed the build script. Now compiles for Scala 2.10 and 2.11 from clean clone.
